// Accounts Module
export const AccountsModuleKeys = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  VIEW_ACCOUNT: 'VIEW_ACCOUNT',
  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  LIST_ACCOUNTS: 'LIST_ACCOUNTS',
} as const;
