// Permissions Module
export const PermissionsModuleKeys = {
  VIEW_PERMISSION: 'VIEW_PERMISSION',
  CREATE_PERMISSION: 'CREATE_PERMISSION',
  UPDATE_PERMISSION: 'UPDATE_PERMISSION',
  LIST_PERMISSIONS: 'LIST_PERMISSIONS',
  DELETE_PERMISSION: 'DELETE_PERMISSION',
  LIST_PERMISSION_MODULE_KEYS: 'LIST_PERMISSION_MODULE_KEYS',
  LIST_PERMISSION_MODULES: 'LIST_PERMISSION_MODULES',
  LIST_PERMISSION_SCOPES: 'LIST_PERMISSION_SCOPES',
  LIST_SCOPED_PERMISSIONS: 'LIST_SCOPED_PERMISSIONS',
} as const;
